#!/usr/bin/env python
# -*- coding: utf-8 -*-
from nltk.stem.wordnet import WordNetLemmatizer
import optparse
import sys
import math
import re
from collections import defaultdict
from itertools import product
numbers=re.compile('\d')
optparser = optparse.OptionParser()
optparser.add_option("-b", "--bitext", dest="bitext", default="data/dev-test-train.de-en", help="Parallel corpus (default data/dev-test-train.de-en)")
optparser.add_option("-n", "--num_sentences", dest="num_sents", default=sys.maxint, type="int", help="Number of sentences to use for training and alignment")
(opts, _) = optparser.parse_args()
lmt= WordNetLemmatizer()

def contains_dig(word):
		return bool(numbers.search(word))
def lem(word):
	word=word.lower()
	mod= normalize(word)
	if (mod==word):
		mod=lmt.lemmatize(word)
		if (mod==word):
			mod=lmt.lemmatize(word,'v')
	return mod
def normalize(word):
	mod=''
	if contains_dig(word):
		mod="0"
	elif (word in ['.',',','!','-',':','?','(',')','[',']',';']):
		mod="."
	else:
		mod= word
	return mod
#wl=['cars','fantasized','12th','87',':','Stabilität']
#print map(lem,wl)

sys.stderr.write("Training with IBM Model1.\n")
sys.stderr.write("Initializing uniform probabilities.\n")
bitext = [[sentence.strip().split() for sentence in pair.split(' ||| ')] for pair in open(opts.bitext)][:opts.num_sents]
lex_prob = defaultdict(float)
word_pairs=[]
f_wrds=defaultdict(list)
for (n, (f, e)) in enumerate(bitext):
	#f=[words.lower() for words in f]
	#e=[words.lower() for words in e]
	f= map(lem,f)
	e= map(lem,e)
	word_pairs.append(list(set(product(f,e))))
	if n % 500 == 0:
		sys.stderr.write(".")
	
word_pairs= set([item for sublist in word_pairs for item in sublist])
for (f,e) in word_pairs:
		f_wrds[f].append(e)
		f_wrds["<nullholder>"].append(e)
f_wrds["<nullholder>"]=list(set(f_wrds["<nullholder>"]))
for f in f_wrds:
		for e in f_wrds[f]:
				lex_prob[(f,e)]=1.0/len(f_wrds[f])
for e in f_wrds["<nullholder>"]:
	lex_prob[("<nullholder>",e)]=1.0/len(f_wrds["<nullholder>"])
sys.stderr.write("\n null prob: "+str(lex_prob[("<nullholder>","the")])+" and "+str(lex_prob[("<nullholder>","book")]))
likelihood=0.0
early_like=0.0
counter=0
while ((likelihood-early_like > 0.5) or (counter<2)):
#while counter<1:
	sys.stderr.write("\nPerforming E step.\n")
	lex_count= defaultdict(float)
	lex_total= defaultdict(float)
	early_like=likelihood
	for (n , (fs,es)) in enumerate(bitext):
		fs.append("<nullholder>")
		#fs= [word.lower() for word in fs]
		#es= [word.lower() for word in es]
		fs=	map(lem,fs)
		es= map(lem,es)
		tot_e=defaultdict(float)
		for (i,e) in enumerate(es):
			tot_e[e]=0.0
			fore=0.0
			for f in fs:
				tot_e[e] += lex_prob[(f,e)]
				fore += lex_prob[(f,e)]
			if (i==0):
				likelihood += math.log(fore)
			else:
				likelihood = likelihood+ math.log(fore)
		for e in es:
			for f in fs:
				lex_count[(f,e)] += lex_prob[(f,e)]/tot_e[e]
				lex_total[f] += lex_prob[(f,e)]/tot_e[e]
		if n%500 ==0:
			sys.stderr.write(".")
	likelihood= likelihood/len(bitext)
	sys.stderr.write("\nPerforming M step.\n")
	for (n,(f,e)) in enumerate(lex_prob):
		lex_prob[(f,e)] = lex_count[(f,e)]/lex_total[f]
		if n%500000 == 0:
			sys.stderr.write(".")
	sys.stderr.write("\n Iteration: "+str(counter)+" Average Likelihood: "+str(likelihood)+" Previous: "+str(early_like)+"\n")
	sys.stderr.write("\n null prob: "+str(lex_prob[("<nullholder>","the")])+" and "+str(lex_prob[("<nullholder>","book")]))
	counter += 1

for (f, e) in bitext:
	#f.append("<nullholder>")
	#e=[word.lower() for word in e]
	#f= [word.lower() for word in f]
	e= map(lem,e)
	f=map(lem,f)
	for (i, e_i) in enumerate(e): 
		scores=[]
		for (j1,f_j) in enumerate(f):
			scores.append(lex_prob[(f_j,e_i)])
		high=max(scores)
		j_l= [(s,abs(i-s)) for s,r in enumerate(scores) if r==high]
		j_l= sorted(j_l,key=lambda x:x[1])
		j= j_l[0][0]
		if (lex_prob[("<nullholder>",e_i)]<scores[j]):
			sys.stdout.write("%i-%i " % (j,i))
		#else:
		#	sys.stderr.write("nooooooooooooooooooooooooooooooooo\n")
	sys.stdout.write("\n")

					
			

