#!/usr/bin/env python
import argparse
import sys
import models
import heapq
from collections import namedtuple

parser = argparse.ArgumentParser(description='Simple phrase based decoder.')
parser.add_argument('-i', '--input', dest='input', default='data/input', help='File containing sentences to translate (default=data/input)')
parser.add_argument('-t', '--translation-model', dest='tm', default='data/tm', help='File containing translation model (default=data/tm)')
parser.add_argument('-s', '--stack-size', dest='s', default=sys.maxint, type=int, help='Maximum stack size (default=1)')
parser.add_argument('-n', '--num_sentences', dest='num_sents', default=sys.maxint, type=int, help='Number of sentences to decode (default=no limit)')
parser.add_argument('-l', '--language-model', dest='lm', default='data/lm', help='File containing ARPA-format language model (default=data/lm)')
parser.add_argument('-v', '--verbose', dest='verbose', action='store_true', default=False,  help='Verbose mode (default=off)')
opts = parser.parse_args()

tm = models.TM(opts.tm, sys.maxint)
lm = models.LM(opts.lm)
sys.stderr.write('Decoding %s...\n' % (opts.input,))
input_sents = [tuple(line.strip().split()) for line in open(opts.input).readlines()[:opts.num_sents]]

hypothesis = namedtuple('hypothesis', 'logprob, lm_state, predecessor, phrase, esp, belong, flipped')
def score(phrase,h,f,j):
	logprob = h.logprob + phrase.logprob
	lm_state = h.lm_state
	for word in phrase.english.split():
		(lm_state, word_logprob) = lm.score(lm_state, word)
		logprob += word_logprob
	logprob += lm.end(lm_state) if j == len(f) else 0.0
	return logprob,lm_state
def extract_english_recursive(h):
	return '' if h.predecessor is None else '%s%s ' % (extract_english_recursive(h.predecessor), h.phrase.english)
def extract_spanish_recursive(h):
	return '' if h.predecessor is None else '%s%s %s ' % (extract_spanish_recursive(h.predecessor), " ".join(h.esp), str(h.flipped))
for f in input_sents:
    # The following code implements a DP monotone decoding
    # algorithm (one that doesn't permute the target phrases).
    # Hence all hypotheses in stacks[i] represent translations of 
    # the first i words of the input sentence.
    # HINT: Generalize this so that stacks[i] contains translations
    # of any i words (remember to keep track of which words those
    # are, and to estimate future costs)
	initial_hypothesis = hypothesis(0.0, lm.begin(), None, None,None,0,0)

	stacks = [{} for _ in f] + [{}]
	stacks[0][lm.begin()] = initial_hypothesis
	for i, stack in enumerate(stacks[:-1]):
	# extend the top s hypotheses in the current stack
		#print "Stuck in", str(i)
		for h in heapq.nlargest(opts.s, stack.itervalues(), key=lambda h: h.logprob): # prune
			h1 = h.predecessor
			for j in xrange(i+1,len(f)+1):
				for flip in [0,1]:
					toconsider=f[i:j]
					#if (flip==0):
					#	toconsider= f[i:j]
					#else:
					#	toconsider= f[i+1:j]+f[i:i+1]
					#toconsider = tuple(toconsider)
					#if f[i:j] in tm:
					if toconsider in tm:
						if (flip ==0):
							for phrase in tm[toconsider]:
								logprob,lm_state = score(phrase,h,f,j)
								new_hypothesis = hypothesis(logprob, lm_state, h, phrase, toconsider, j,0)
								if lm_state not in stacks[j] or stacks[j][lm_state].logprob < logprob: # second case is recombination
									stacks[j][lm_state] = new_hypothesis
									
						#Handle skipping now!!			
						elif (flip==1):
							#if (h.flipped==1):
							#	continue
							for phrase in tm[toconsider]:
								for k in xrange(j+1,len(f)+1):
									skipconsider= f[j:k]
									if skipconsider in tm:
										for phrase2 in tm[skipconsider]:
											logprob,lm_state= score(phrase2,h,f,i+k-j)
											new_hypothesis = hypothesis(logprob,lm_state,h,phrase2,skipconsider,i+k-j,1)
											#Translating skipped phrase now
											logprob,lm_state = score(phrase,new_hypothesis,f,k)
											newer_hypothesis = hypothesis(logprob, lm_state,new_hypothesis,phrase,toconsider,k,1)
											if lm_state not in stacks[k] or stacks[k][lm_state].logprob < logprob:
												stacks[k][lm_state] = newer_hypothesis
									

	# find best translation by looking at the best scoring hypothesis
	# on the last stack
	winner = max(stacks[-1].itervalues(), key=lambda h: h.logprob)
	#print winner
	print extract_english_recursive(winner)
	sys.stderr.write(extract_english_recursive(winner)+"\n")
	sys.stderr.write(extract_spanish_recursive(winner)+"\n")
	sys.stderr.write(" ".join(f)+"\n")
	if opts.verbose:
		def extract_tm_logprob(h):
			return 0.0 if h.predecessor is None else h.phrase.logprob + extract_tm_logprob(h.predecessor)
		tm_logprob = extract_tm_logprob(winner)
		sys.stderr.write('LM = %f, TM = %f, Total = %f\n' % 
            (winner.logprob - tm_logprob, tm_logprob, winner.logprob))
